# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRs2LksiV6J4i8jX4CbvI-lw157j7a7z
"""

import requests
with open('New Text Document.txt',mode = 'rb') as file:
  post_body = file.read()
api_url = "https://www.summarizebot.com/api/summarize?apiKey=748baf41ec7d4b5a853dedecaa4b5a41&size=20&keywords=10&fragments=15&filename=New Text Document.txt"

header = {'Content-Type': "application/octet-stream"}
r = requests.post(api_url, headers = header, data = post_body)
json_res = r.json()
s = json_res

s[0]['summary']

k=''
for i in range(len(s[0]['summary'])):
  k+=s[0]['summary'][i]['sentence']


