# -*- coding: utf-8 -*-
"""similaritycheck

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mmB7-AbkVCaPxQPU2F9EXUk1ezZmd_qt
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize

text_files = open("New Text Document.txt").read()

c = sent_tokenize(text_files)

tfidf = TfidfVectorizer().fit_transform(c)
# no need to normalize, since Vectorizer will return normalized tf-idf
pairwise_similarity = tfidf * tfidf.T

vect = TfidfVectorizer(min_df=1)

tfidf = vect.fit_transform(c)

k=(tfidf * tfidf.T).A

k=list(k[0])

k = sorted(k)
l = k[len(k)/2]

s=''
for i in range(len(k)):
  if(k[i]<l):
    s+=c[i]
print(s)

